[mcp_servers.atlassian]
url = "https://mcp.atlassian.com/v1/mcp/authv2"
enabled = true
required = false
startup_timeout_sec = 20
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"

[mcp_servers.atlassian_api_token]
url = "https://mcp.atlassian.com/v1/mcp"
enabled = false
required = false
startup_timeout_sec = 20
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"
env_http_headers = { Authorization = "ATLASSIAN_MCP_AUTHORIZATION" }

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_PAT_TOKEN"
enabled = true
required = false
startup_timeout_sec = 20
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"
