-- NorthStar proposed reviewed-rule delta: Volkswagen -> TecDoc "VW" bridge
--
-- PROPOSAL. Not generated by the rule-export pipeline. Review before applying,
-- and set :target_version to a name that follows the reviewed-version
-- convention for the environment.
--
-- Why this rule exists
--   Transportstyrelsen canonicalises the marque to "Volkswagen"; the pinned
--   TecDoc 0326 catalog registers it as "VW". No reviewed rule currently
--   produces "VW" and none carries "VW" as a source term, so nothing bridges
--   the two vocabularies. Every affected car resolves to global manufacturer
--   scope and is reviewed WITHOUT being scored.
--
-- Evidence
--   * base_manufacturer is populated on 2.04% of passenger rows; brand on 100%.
--   * The TS brand text corroborates the identity directly: "VOLKSWAGEN, VW 3C".
--   * Measured against the pinned catalog, manufacturer resolution over the
--     top-400 brand strings (4,796,674 cars) rises from 88.4% to 99.9%.
--   * ~557,000 cars currently cannot be scored at all for this reason.
--
-- The rule is a whole-token-prefix manufacturer entity, not a substring guess.
-- Its source_term matches a catalog manufacturer, so TecDocManufacturerIndex
-- bridges canonical "Volkswagen" onto catalog "VW" through its existing
-- canonical_bridges path. No application code change is required.

-- Set the reviewed version name for this activation before running, e.g.
--   psql -v ON_ERROR_STOP=1 \
--        -c "SET northstar.target_version = 'ts-review-20260821T090000000000Z'" \
--        -f outputs/proposed/ts-tecdoc-vw-manufacturer-bridge.sql
-- or edit the SET LOCAL line below.

\set ON_ERROR_STOP on

BEGIN;

SET LOCAL northstar.target_version = 'ts-review-REPLACE-WITH-CONVENTIONAL-VERSION';

LOCK TABLE core.translation_rule_versions IN SHARE ROW EXCLUSIVE MODE;

DO $northstar_vw_bridge$
DECLARE
    target_version CONSTANT text := current_setting('northstar.target_version');
    active_base text;
    active_overrides jsonb;
    new_rule CONSTANT jsonb := jsonb_build_object(
        'kind', 'manufacturer_entity',
        'entity_role', 'vehicle_manufacturer',
        'entity_id', 'MFE-BRAND-VW-SHORT-NAME',
        'match_type', 'whole_token_prefix',
        'source_field', 'brand',
        'source_term', 'VW',
        'canonical_name', 'Volkswagen',
        'base_behavior', 'use_entity',
        'change_note', 'TS brand short name for Volkswagen; bridges the canonical name onto the TecDoc catalog name VW.'
    );
BEGIN
    SELECT base_rule_version, overrides
      INTO active_base, active_overrides
      FROM core.translation_rule_versions
     ORDER BY activated_at DESC, version DESC
     LIMIT 1;

    IF active_base IS NULL THEN
        RAISE EXCEPTION 'no activated rule version to extend';
    END IF;

    IF active_overrides ? 'MFE-BRAND-VW-SHORT-NAME' THEN
        RAISE EXCEPTION 'MFE-BRAND-VW-SHORT-NAME is already active; nothing to apply';
    END IF;

    INSERT INTO core.translation_rule_versions
        (version, base_rule_version, overrides, activation_note, activated_at)
    VALUES (
        target_version,
        active_base,
        active_overrides || jsonb_build_object('MFE-BRAND-VW-SHORT-NAME', new_rule),
        'Add reviewed Volkswagen short-name rule bridging the canonical name to TecDoc catalog name VW.',
        now()
    );
END
$northstar_vw_bridge$;

COMMIT;
